### ISSUE TITLE
Develop and submit MCW annotators

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#12]
@gkowalski Is it possible for you to create one or more annotators (date, person name and/or physical address annotators), associate them to an "MCW" team on Synapse and submit them for evaluation so that they appear in the leaderboard tables when we launch the NLP Sandbox?

**Comment by gkowalski** [comment]
Sure that was the goal . I hope Synapse is up and running ...

**Comment by gkowalski** [comment]
I have submitted a first docker.synapse.org/syn22277847/mcw-date-annotator , which is just a fork of the existing https://github.com/nlpsandbox/date-annotator-example

**Comment by gkowalski** [comment]
![Screen Shot 2021-01-28 at 10 13 35 AM](https://user-images.githubusercontent.com/617805/106173426-8669db00-6159-11eb-8e5b-2f98f3758719.png)

I have no permission

![Screen Shot 2021-01-28 at 10 13 22 AM](https://user-images.githubusercontent.com/617805/106173462-91247000-6159-11eb-9089-ada02556f04a.png)

**Comment by gkowalski** [comment]
Believe this is done for at least one
