### ISSUE TITLE
Develop and submit UW annotators

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#14]
@yy6linda Do you know someone at UW (researchers and/or fellow students) who may be interested in building and submitting an annotators to the NLP Sandbox?

**Comment by yy6linda** [comment]
I don't have any names out of my head but I can share the news with some research groups at UW working on clinical notes de-identification to see if they are interested.

**Comment by tschaffter** [comment]
On January 25, Justin shared with me:

> Meliha presented her work today on the iEC NLP call; she has developed a corpora for assessing de-id on their UW cohort. She is interested in working with others who want to use this dataset for benchmarking.

My idea is to wait for the launch of the NLP Sandbox in a week and then contact Meliha and show her the NLP Sandbox.
