### ISSUE TITLE
Write down a comprehensive description of each performance metric

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#17]
no weekly update as we do in the COVID-19 challenge

**Comment by thomasyu888** [comment]
@tschaffter This is dependent on https://github.com/nlpsandbox/nlpsandbox-controller/issues/42.  The leaderboard submission view can be found here: https://www.synapse.org/#!Synapse:syn23747126/tables/.

<img width="734" alt="Screen Shot 2021-01-08 at 1 49 39 PM" src="https://user-images.githubusercontent.com/10556275/103979372-a6d8f200-51b8-11eb-8dae-64d51bf43e8a.png">

From the linked issue, please clarify the following:

* F1 score (date format) - is optional and if not submitted then NA?
* F1 score (patient/doctor) - is optional too?  If not submitted then NA?
* F1 score (HIPAA PHI or not) /  (sub-category) - Not sure what these are. 

All I know for certain is that I have:

```
location_F1_instance_relax
location_F1_instance_strict
location_F1_token_strict
location_precision_instance_relax
location_precision_instance_strict
location_precision_token_strict
location_recall_instance_relax
location_recall_instance_strict
location_recall_token_strict
```

**Comment by tschaffter** [comment]
@thomasyu888 

> F1 score (date format) - is optional and if not submitted then NA?

Date annotation task only: If the gold standard includes at least one `dateFormat` value, then compute `date_format_F1`, `date_format_recall`, `date_format_precision` (here there is no need to do a distinction between instance/token or relax/strict).

> F1 score (patient/doctor) - is optional too? If not submitted then NA?

Person name annotation task only: Just ignore this case. We haven't settled yet on how to model the "type of person".

> F1 score (HIPAA PHI or not) / (sub-category) - Not sure what these are.

Physical address annotation task only: If the gold standard includes at least one [addressType](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/7b1d1cd54d98b754262ad75af289de792f6f4971/openapi/commons/components/schemas/TextPhysicalAddressAnnotation.yaml#L7) value, then compute `address_type_F1`, `address_type_precision` and `address_type_recall`.

**Comment by thomasyu888** [comment]
@tschaffter 
Thanks, the leaderboards can be found [here](https://www.synapse.org/#!Synapse:syn22277124/wiki/607367).  They are just under Internal subpages, but we can easily shift them to a different wiki page.  Here are a couple of action items that we need to do.

1. I think it will help me if I was able to get the output of the evaluator in all of these scenarios.  That would help me the most when creating the leaderboards as the most important thing is actually the annotation key that is added to the submission.
2. Need to dry-run the person and address baseline models.  I haven't had the opportunity to rebuild and run those.

If you are happy with the leaderboards on the wiki page, please close this issue.

**Comment by tschaffter** [comment]
> F1 score (HIPAA PHI or not) / (sub-category) - Not sure what these are.

Complement to the above answer: The "HIPAA" category is when doing the evaluation only for address objects that are covered by the HIPAA standard. @yy6linda knows which address types to consider. Currently, the non-HIPAA case correspond to the "I2B2" category.

**Comment by tschaffter** [comment]
I don't see the leaderboard when following the above link

![image](https://user-images.githubusercontent.com/3056480/103980905-992e5880-5135-11eb-8888-dae25b00aa51.png)

@yy6linda Please review the comments posted by Tom. Also, consider adding the keyword "i2b2" to all the non-HIPAA categories to be consistent. Adopt a common variable name schema like (location|date_format|address_type) + "_" + (i2b2|hipaa) + "_" + (F1|precision|recall) + other categories when applicable.

**Comment by thomasyu888** [comment]
@tschaffter, Its in the sub pages.

**Comment by thomasyu888** [comment]
For discussion, this is what each annotation type's scoring returns:

* date
```json
{"date_location": ["..."],
 "date_type": ["..."]}
```


* person

```json
{"person_location": ["..."],
 "person_type": ["..."]}
```

* address
```json
{"address_location": ["..."],
 "address_type": ["..."]}
```

**Comment by tschaffter** [comment]
@thomasyu888 Following a stand up meeting with @yy6linda , she will write down a comprehensive description of each performance metrics / categories and how they are computed. I will then review this proposal before we move on with the completion of its implementation.

**Comment by tschaffter** [comment]
@thomasyu888 @yy6linda I initially created this ticket to highlight the *live* aspect of the leaderboard table. I've renamed this ticket to better describe the recent discussion on the content of the leaderboards.

@thomasyu888 My understanding is that the leaderboard tables you have shown are live (i.e. continuously updated). Can you confirm that this is correct, in which case we do not need to open a ticket to make the leaderboard live because they already are.

**Comment by yy6linda** [comment]
I added a [description](https://docs.google.com/document/d/1R1pQRx-6iURjJmmtLyGXVAMMA0ulD3RygHJc_dQ14hw/edit#) (under `leaderboard outlook`) of how each scoring matrix is calculated based on current [goldstandard](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/example-patient-bundles.json).

**Comment by tschaffter** [comment]
@yy6linda Your first link does not point to a specific section

**Comment by yy6linda** [comment]
@tschaffter  Just updated the link

**Comment by tschaffter** [comment]
We have draft of the documentation on evaluation. We will further improve it as we work on the Synapse wiki pages.
