### ISSUE TITLE
Create Google form to collect log requests

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#19]
## Motivation

In most model-to-data challenges, the Synapse discussion forum gets quickly cluttered with messages asking the organizers to return the logs of a given submission. In order to clutter the discussion space, the idea is to create a form that participant can fill in to request logs or help with a submission. The information that we must collect are

- Synapse submission ID
- Synapse username, logs will be return to `<username>@synapse.org`

We will check manually or programmatically (preferred) that the specified user is the submitter or a member of the submitting team (this test should now be part of the SOP for returning logs). Organizers will regularly check the Google form, get the logs and decide what can be communicated to the requester.

## Task

- [x] Create a Google form that ask for submission Id and contact information
- [x] Create a post on in the discussion forum with a link to the form + pin the post

**Comment by tschaffter** [comment]
@thomasyu888 Since you have experience assisting challenge participants, how does this way of doing sounds? I was thinking to use GitHub to track these requests but at this point I don't really see an advantage doing so.

**Comment by ychae** [comment]
@tschaffter Here's the first pass of the [Google form](https://docs.google.com/forms/d/1XgPr7XcXjGdanordZQLCr9gLCGOPSMWK1SsNJcUZbSA/edit) for review.

**Comment by tschaffter** [comment]
I made some changes. It looks good! Can we configure the form to send a notification to Tom, Yao and myself when someone submit a request?

**Comment by tschaffter** [comment]
Task 1 checked

**Comment by ychae** [comment]
Okay I turned on email notifications for new responses. I need to test whether it only gets sent to me or to all collaborators.

**Comment by ychae** [comment]
@tschaffter this is the message that users see when they submit, is the copy okay?

`Thank you for your request! Please expect to hear from us in the next 2-3 business days. `

**Comment by tschaffter** [comment]
I would go for 1-3 business day.

**Comment by tschaffter** [comment]
@ychae Let me know when this ticket is ready to be closed.

**Comment by ychae** [comment]
Here are the relevant links:
 - [Google form](https://docs.google.com/forms/d/e/1FAIpQLSch30S2FZQoeQNAIyRmrhHphO2Uq-lBERA_8C0deU6IjITA4Q/viewform)
 - [Sheet of responses](https://docs.google.com/spreadsheets/d/1XboWcUgBPbpOqDPDPATgGUdQ2pKQKk9vsRGsSA0MA78/edit#gid=125554388)
 
I added in a column with dropdown values to track who has responded to each request. For notifications, each person who would like to receive a notification needs to set it themselves in the [Google Sheet](https://docs.google.com/spreadsheets/d/1XboWcUgBPbpOqDPDPATgGUdQ2pKQKk9vsRGsSA0MA78/edit#gid=125554388) (as this [Support doc notes](https://support.google.com/docs/answer/91588), you can only set notifications for yourself and not for others). You can use the steps in the [Google support doc](https://support.google.com/docs/answer/91588) to set notifications for yourself from the google sheet every time it updates or a daily digest.

**Comment by ychae** [comment]
[Discussion post](https://www.synapse.org/#!Synapse:syn22277124/discussion/threadId=7773) has been created although I wasn't able to pin it (I believe only admins can pin discussion posts).

<img width="1017" alt="Screen Shot 2021-02-17 at 2 26 44 PM" src="https://user-images.githubusercontent.com/12868382/108276324-7deb3b80-712c-11eb-834f-4ad17b71d52b.png">

**Comment by tschaffter** [comment]
The message looks good! We can add it as it is to the [production site](https://www.synapse.org/#!Synapse:syn22277123/wiki/604824).

**Comment by ychae** [comment]
Here's the discussion post in the prod site: https://www.synapse.org/#!Synapse:syn22277123/discussion/threadId=7774

**Comment by tschaffter** [comment]
This ticket is now complete. Thanks!
