### ISSUE TITLE
Deploy EC2 with example implementations

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#27]
The project documentation relies on the following three services

- Date Annotator stub, which is straight out of the generator to show the user the "do so magic!" responses
- Date Annotator Example
- PHI Deidentifier React app

I'm considering:

1. deploying these apps on the same EC2
2. place a load balancer that redirects tools.nlpsandbox.io to the EC2
3. Use nginx to setup the current redirections
  - tools.nlpsandbox.io/phi-deidentifier
  - tools.nlpsandbox.io/date-annotator-example
  - tools.nlpsandbox.io/date-annotator-stub

**Comment by thomasyu888** [comment]
Let me know when you set up the docker compose, I will add this to the things I set up in my cloud formation stack.

**Comment by tschaffter** [comment]
I created this dockerized stub for the Date Annotator:
https://github.com/nlpsandbox/date-annotator-stub

**Comment by tschaffter** [comment]
Replaced by these tickets:

- https://github.com/nlpsandbox/aws-cloudformation/issues/2
- https://github.com/nlpsandbox/aws-cloudformation/issues/3
- https://github.com/nlpsandbox/aws-cloudformation/issues/4
