### ISSUE TITLE
Team review of the website

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#30]
Thanks for accepting to review pages of the website. As requested, here are the assignments to review specific pages:

- [NLP Sandbox Staging site](https://www.synapse.org/#!Synapse:syn22277124/wiki/604825)
- Submit your review as a PR that target the branch `staging` of the repository [nlpsandbox/nlpsandbox-website-synapse](https://github.com/nlpsandbox/nlpsandbox-website-synapse)

Please submit your review by the end of Monday March 8.

Website sections to review:

- Tasks: @ymnliu @cascadianblue 
- How to Participate: @ymnliu @yy6linda
- Datasets: @cascadianblue 
- Rules: @yy6linda 

If you have any question on how to submit your review, just let me know and I will be happy to jump in a 15-min call to show you.

**Comment by ymnliu** [comment]
@tschaffter may you grant me access to the page? My synapse user name is `ymnliu`, the same as GitHub. 

I am seeing a message `You are not authorized to access the page requested.`

**Comment by tschaffter** [comment]
@ymnliu I sent you an invite to join the Synapse team [NLP Sandbox Team](https://www.synapse.org/#!Team:3413390). You will have access to the NLP Sandbox staging site once you have accepted the invite.

**Comment by tschaffter** [comment]
Done
