### ISSUE TITLE
Create a graph of the ecosystem

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#36]
Create a graph similar to the one James presented for the HTAN project. This graph should also include the GitHub repositories and the artifacts that they publish (Docker image, GitHub Pages, etc.).

Here are a few Lucidcharts we can start from:

- [NLP Sandbox: Infrastructure](https://lucid.app/lucidchart/04ca1c37-754b-4c6b-b6f3-53a10aad28f5/edit?page=0_0#)

**Comment by tschaffter** [comment]
@thomasyu888 What was the link you shared with me yesterday when James presented his diagram?

**Comment by thomasyu888** [comment]
@tschaffter , not sure what link I actually shared...

**Comment by tschaffter** [comment]
Now tracked in #39
