### ISSUE TITLE
Confirm with Sage governance team that MCW is in good standing with us

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#52]
From past discussion, Bradley Taylor said that he does not require an agreement to be in place for his group to deploy the NLP Sandbox infrastructure at MCW and start evaluating the performance of submitted tools.

### TODO

- Confirm with Sage governance team that we indeed don't need an agreement to be put in place if MCW does not require one.

Tagging @gkowalski

**Comment by tschaffter** [comment]
@jiaxinmachine88 Can we close this ticket?

**Comment by jiaxinmachine88** [comment]
This can be closed
