### ISSUE TITLE
Create YouTube account / channel

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#53]
Either create a dedicated YT account or create a playlist in Sage Bionetworks account. The former may give us more freedom when upload video quickly given the short timeline.

Related to #10

**Comment by jiaxinmachine88** [comment]
@tschaffter it might be useful to include the [Get Started with Synapse documentation ](https://help.synapse.org/docs/Getting-Started.2055471150.html)

**Comment by tschaffter** [comment]
@jiaxinmachine88 Good point. The doc site wasn't available when we wrote the NLP Sandbox doc.

### TODO

- [ ] Mention new Synapse doc in on NLPSandbox.io

**Comment by jiaxinmachine88** [comment]
FYI, YouTube Guidelines from Hsiao-Ching: "We can upload videos to the Sage YouTube channel. Videos need to be well-lit and have great audio. If there’s a script, please share the script so that it can be uploaded for the transcript (for accessibility purposes)."

**Comment by tschaffter** [comment]
### Update

I tried to create the account "nlpsandbox@gmail.com" but it's already taken. I set an email to this address to ask if the own would consider giving us control over this account. Waiting on an answer.

EDIT:

> Your message wasn't delivered to nlpsandbox@gmail.com because the address couldn't be found, or is unable to receive mail.

**Comment by tschaffter** [comment]
See [A Gmail username is already taken, but email does not exists](https://support.google.com/mail/forum/AAAAK7un8RU2VjA-eWImRw/?hl=en&msgid=sMPCvsHJCAAJ&gpf=d/msg/gmail/2VjA-eWImRw/sMPCvsHJCAAJ)

**Comment by tschaffter** [comment]
I was able to create the account `nlpsandbox.io@gmail.com`. On YT, I get an error when trying to create the channel. Will try again a few hours after the creation of the google account.

**Comment by tschaffter** [comment]
Done: https://www.youtube.com/channel/UCmOrQIvlfpFzNfclnI_-Kog
