### ISSUE TITLE
Create NLP article to be published to NCATS Ansible

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#55]
### TODO

- @tschaffter to review the current draft - make sure my name and Sage Bionetworks are mentioned to help clarifying lingering confusion between our work (NLP Sanbdox) and Hongfang's work (N3C-NLP).
- @jiaxinmachine88 to add a reference to "Thomas Schaffter" and "Sage Bionetworks".

**Comment by jiaxinmachine88** [comment]
Please take a read by EOW (Andrea would like everything to be signed off by Monday June 7th): 
https://docs.google.com/document/d/19TibMEXgfsW0od6Rp0ZXu5rFBmc2ZWnpReOxBthdeFI/edit?ts=60afde20

**Comment by tschaffter** [comment]
@jiaxinmachine88 Changes to make:

> Led by Thomas Schaffter at Sage Bionetworks

Since the article specifies Hongfang's title, let's also include mine (use either the prefix "Dr." or the suffix "PhD")

We are currently using three different ways to refer to the NLP Sandbox and I'm wondering if we should converge to only two:

1. NLPSandbox.io => That's the full name of the service and the address of the website. It makes sense to continue using it.
2. NLPSandbox
3. NLP Sandbox

Between Option 2 and 3, is may be easier and more intuitive to write "... the NLP Sandbox...". What do you think? If we keep Option 1 and 3, then occurrences of "NLPSandbox" in the article should be replaced by "the NLP Sandbox".
