### ISSUE TITLE
Review approach for submitting models on behalf of the NLP Sandbox Team

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#56]
Currently, submission are made on behalf of the NLP Sandbox Team, which include the developers of the NLP Sandbox. I proposed this approach to enable the users to clearly identify the tools that we submit in the leaderboard table.

I have two potential concerns:

- I don't want all the members of the NLP Sandbox Team to receive a message each time we submit a model. @thomasyu888 Can you confirm that the current behavior is email sent to all the members?
- A few members of the team need to be able to submit models on their behalf or on behalf of their respective organization. I believe that the current behavior is that a member from the NLP Sandbox team cannot make a submission as an individual or as a member of another submitting team. @thomasyu888 can you confirm this? While initially I thought that this is great to prevent NLP Sandbox members to be part of a participating team, who are not eligible for "incentives", this approach reduce the freedom of members who want to play with the NLP Sandbox. We should just make sure that they don't publish a model that achieve "unfair" performance thanks to insider information.

Unless my assympting/recollection of how Synapse submission work are inaccurate, I propose to create a team dedicate to make these submission and thus prevent members to receive submission emails and being blocked from submitting on their own. Shall we call the team NLP Sandbox Bot - or NLP Sandbox Bots - and make the submission on behalf of the bot?

**Comment by thomasyu888** [comment]
@tschaffter 

> Can you confirm that the current behavior is email sent to all the members?

Yes this is a Synapse behavior when you submit on behalf of the team, everyone on the team gets an automated email from Synapse

> I believe that the current behavior is that a member from the NLP Sandbox team cannot make a submission as an individual or as a member of another submitting team. can you confirm this? 

Yes that is the case

> I propose to create a team dedicate to make these submission and thus prevent members to receive submission emails

Yes, we can definitely do this, we already have a `nlp-sandbox-bot` admin user that we can actually submit to the challenge as.   Did we want to use that?  This way we can all still submit as individuals.  I'm also happy to create a NLP sandbox bot team with just the two of us on the team?

**Comment by tschaffter** [comment]
> I'm also happy to create a NLP sandbox bot team with just the two of us on the team?

@thomasyu888 Let's do that! We could also include the bot in the team. One advantage of submitting as a Team is that we can control the submitter name displayed in the leaderboard (i.e. the name of the team while individual username are fixed).

**Comment by thomasyu888** [comment]
> @tschaffter individual username are fixed

This is not true. Synapse usernames can be changed at any time, Synapse userids are fixed.  That being said, lets create a team.  What do you want the team to be called?

**Comment by tschaffter** [comment]
@thomasyu888 "NLP Sandbox Bots"

**Comment by thomasyu888** [comment]
Created "NLP Sandbox Bots" team.
