### ISSUE TITLE
Deploy Data Hosting Site at MCW

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#6]
@gkowalski What can we do in order to deploy one day our benchmarking infrastructure at MCW so that tools submitted for evaluation can be evaluated on private, MCW data?

**Comment by gkowalski** [comment]
We need to come up with documentation on how that is done first. Then I can then take that and work with our Sysadmin to get it deployed at MCW.  We generally like to work on Linux boxes, but we can get Windows if necessary for some reason. Dockerized solutions like we have should run anywhere.

**Comment by tschaffter** [comment]
There are two types of documentation required:

- How to prepare a dataset for one or more annotation tasks
- How to deploy the benchmarking infrastructure on MCW

I'll shortly create a ticket to track the preparation of the dataset preparation SOP.

The documentation on how to deploy the benchmarking infrastructure will be provided here: https://github.com/nlpsandbox/nlpsandbox-controller. There are still quite some work going on to complete the first version of the infrastructure. However even if the documentation is not ready and if it works for you, we could in 1-2 weeks start guiding you to deploy the infrastructure on MCW on-premise or cloud servers.

@thomasyu888 Does it makes sense to start deploying the infrastructure on MCW sooner than later, e.g. to test that we can support multi-site evaluation? However this should not come at the cost of eating to much of your time at the point of delaying development.

**Comment by gkowalski** [comment]
What annotation Types , PERSON , DOCTOR , LOCATION, etc are needed for our notes we're submitting ?

**Comment by tschaffter** [comment]
@gkowalski The [NLP Sandbox schemas](https://github.com/nlpsandbox/nlpsandbox-schemas) is the reference for questions about the data and tool specification. The output of the person name annotator is defined [here](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/aa5ed8857a2afb63f56f681729b4ce645ca88487/openapi/person-name-annotator/paths/textPersonNameAnnotations.yaml#L18), which in turns lead to the schema [TextPersonNameAnnotation](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/schemas/TextPersonNameAnnotation.yaml) (long intro but hopefully may help to answer future questions).

Currently the gold standard and predicted person name annotations do not capture the type values PATIENT and DOCTOR included in the i2b2 dataset. The reason is because I think that a "person type" should not be a property of a "person name annotation". However, if we consider at some point a *person annotator* (and not *person name annotator*), then this annotator would probably be asked to generate one object per person mentioned in the note. In this case, including that describe the person type would make sense to me. We could also ask the person annotator to provide for each person object generated an array of *person name annotations* that refer to this person.

Regarding your mention of LOCATION, this i2b2 annotation correspond to our [physical address annotator](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/schemas/TextPhysicalAddressAnnotation.yaml). For info, the property `addressType` may be renamed `type` in the next schemas release to be compliant with a recent change in the convention used to write the schemas.

Tagging @cascadianblue @ymnliu @yy6linda as the above paragraphs mention a potential new annotator (person annotator that would be different from (or replace) person name annotator).

**Comment by tschaffter** [comment]
Virtually done. MCW has prepared a dataset to enable the benchmarking of PHI annotator and is now fine tuning the benchmarking infrastructure on their site.
