### ISSUE TITLE
Get permission to redistribute modified version of 2014 i2b2 dataset

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#62]
Original dataset is hosted [here](https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/)

### Issue

The website hosting the 7-years-old data ask us to not redistribute the dataset. This public dataset, which does not contain sensitive information, is used in the NLP Sandbox to test the submitted tools before they are shipped to external data site. Ideally, we would like to return logs to the submitters to let them know why their tool failed. However, returning log results in a risk of the developer retrieve the dataset via the log. The risk is low but to comply with the agreement, we should probably keep the log turned off. However, being able to return the log would be a very valuable source of information for developers.

Also, as part of the documentation of the NLP Sandbox, it would be easier if we could show samples of the dataset to the developers. This would required being authorize to redistribute part of (e.g. data from 10 patients) or all the dataset, which once again can be found publicly on the official website.

Now, the NLP Sandbox uses a modified version of the dataset that meet the requirements set by the NLP Sandbox Schemas. The mapping from the original format to the NLP Sandbox format is done here: https://github.com/nlpsandbox/i2b2-phi-dataset

What we are interested in is to redistribute part or ideally all the modified dataset to the developers for the sake of better documentation and speeding up the resolution of issues related to submitted tools that failed.

**Comment by thomasyu888** [comment]
@tschaffter Currently the returning of logs is done manually as stated in in this [synapse wiki](https://www.synapse.org/#!Synapse:syn22277124/wiki/608145)

**Comment by jiaxinmachine88** [comment]
Received initial "no" response; emailed back with additional clarifying points from the issue above on Wed 6/2.

**Comment by jiaxinmachine88** [comment]
Harvard did not approve our request for exemption. Thomas has been updating the documentation with the Harvard dataset terms of use to get ahead of this. Closing issue for now.
