### ISSUE TITLE
Write Sage blog post

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#67]
Published to https://sagebionetworks.org/news/

**Comment by tschaffter** [comment]
@jiaxinmachine88 to ask if there is a system in place to track analytics data on sage main website as well as on Synapse.

**Comment by jiaxinmachine88** [comment]
@tschaffter can you review this blog post before Thursday morning? To give Hsiao-Ching time for one final read (she's made a lot of edits already to make it concise and punchy)! 

https://docs.google.com/document/d/1xDlwDl6dW6nhVo4CSF7RjpT-TLtJJbrM-P6XKHxDunI/edit
