### ISSUE TITLE
Identify how to track analytics information

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#68]
Information that would be useful to track:

1. Number  of visit to the Sage blog page and where do the visitors come from
2. Same information for the Synapse project behind nlpsandbox.io

@jiaxinmachine88 to ask Hsiao-Ching about how to do 1.
@tschaffter to  ask Bruce about 2.

**Comment by jiaxinmachine88** [comment]
Synapse has google analytics; Nick on the platform team has agreed to share before and after stats in a CSV file with me.
