### ISSUE TITLE
Set submission quota to 1 submission / team / day

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#69]
This is to make life easier to developers at least during the first 1-2 months following the launch of the project.

- [x] @thomasyu888 to update the quota settingss
- [x] @tschaffter to update the documentation on nlpsanbox.io

**Comment by thomasyu888** [comment]
@tschaffter I'm going to set the quota to be this until end of August. Due to the new evaluation endpoint, once there are submissions to the queue, it is difficult to change the quota.  I think there is a bug that I need to file with platform.

**Comment by tschaffter** [comment]
@thomasyu888 What is the protocol if we want to update the submission quota before end of August?

**Comment by thomasyu888** [comment]
It currently isn't possible if there are submissions.   It's something that has to be worked out with platform, but basically once you start a round, you can't seem to modify the round until it ends (if there are submissions).

You can delete all submissions for that round and you can modify the quota.

**Comment by tschaffter** [comment]
@thomasyu888 By "deleting all submissions", you mean making sure that there are no longer "pending" submission in the queue? Your not saying that scored submission need to be remove, correct?

**Comment by thomasyu888** [comment]
@tschaffter With the current infrastructure, ALL submissions have to be removed.  Not just pending submissions.   It's probably worth filing a Jira ticket with platform about this. (I just discovered this today)

**Comment by tschaffter** [comment]
Enabling to update submission quota for existing queue is tracked [here](https://sagebionetworks.jira.com/browse/PLFM-6779).
