### ISSUE TITLE
Create thumbnail and title page for YT videos

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#71]
https://sagebionetworks.jira.com/browse/DESIGN-377

**Comment by tschaffter** [comment]
Let's first create video, then review if title pages are needed.

**Comment by jiaxinmachine88** [comment]
Closing out, Stockard delivered this work for us here: [NLP Sandbox YouTube Thumbnail](https://sagebionetworks.jira.com/browse/DESIGN-379?focusedCommentId=133735&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-133735)
