### ISSUE TITLE
Introduce Monument of NLP Heroes

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#73]
Every month, write on a stone slab - a markdown table - the name of the best-performing teams for each task. The "stone slab" will remain over time, enabling best-performers to apply their "right to boast" for a given month. They may also include in their resume that they were the best performing team for a given task at a given time point or for N consecutive weeks. Ultimately we will provide an API that allows developers to include NLP Sandbox badges on their README that show this information. This feature should promote developers to submit to the NLP Sandbox and keep their tools up to date with the latest NLP Sandbox tool specifications.

For now, this Monument of NLP Heroes will be a markdown table on NLPSandbox.io.

Alternative name: Hall of NLP Heroes

Idea inspired from [SAO's Monument of Swordmen](https://swordartonline.fandom.com/wiki/Monument_of_Swordsmen)

![image](https://user-images.githubusercontent.com/3056480/120930587-ce1de780-c6a2-11eb-9b26-dff5952968af.png)

Tagging @nlpsandbox/team for feedback

**Comment by thomasyu888** [comment]
I like this idea, will this be a separate wiki page?

**Comment by tschaffter** [comment]
@thomasyu888 Yes, it would be on a different page than the existing leaderboards.

**Comment by tschaffter** [comment]
Added to the home page
