### ISSUE TITLE
Need a Whitelist for data-node sites for access control

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox#77]
### Describe the solution you'd like

We here at MCW require a white list of sites the data-node needs to communicate to / from when downloading code to be run and delivering results back to sagebase . In this way we can lock down access to that list for all the data-node docker images and prevent accidental release of data outside the network. 

### Describe alternatives you've considered

This is a requirement given the open nature of the code we'll be downloading and executing.

**Comment by thomasyu888** [comment]
Technically, the data node doesn't interact with any site, but the orchestrator and its workflow does.

- dockerhub
- Services all talk to each other (ELK, datanode, orchestrator)
- Annotation Service + curl commands to the annotation service (all on the same instance, not external) .  The annotation service is ran on an internal docker network called `submission` so the service doesn't have any access.
- Synapse
  ```
  {'repoEndpoint': 'https://repo-prod.prod.sagebase.org/repo/v1',
   'authEndpoint': 'https://auth-prod.prod.sagebase.org/auth/v1',
   'fileHandleEndpoint': 'https://file-prod.prod.sagebase.org/file/v1',
   'portalEndpoint': 'https://www.synapse.org/'}
   ```
- Github
  ```
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/annotate_submission.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/set_permissions.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/get_docker_config.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/score_email.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/submit_to_challenge.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/get_submission.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/validate_docker.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/validate_email.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/check_status.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/upload_to_synapse.cwl
  https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/v3.1/cwl/score_email.cwl
  ```

**Comment by gkowalski** [comment]
So the downloaded docker images from a random person only has access to the "submission" docker network ? Thought we went thru some work to give it access to other docker images on localhost:8080 ?

**Comment by gkowalski** [comment]
We are setting up access rules to the above web sites , but we cannot grant access to particular URL's like https://raw.githubusercontent.com/Sage-Bionetworks/ChallengeWorkflowTemplates/ so we are addressing access to raw.githubusercontent.com in another way that will take a day or 2 to implement.  Our data node will be down when we are not online to monitor it.  which is 8:00am - 5:00pm CDT

**Comment by gkowalski** [comment]
We are finding quite a bit more in terms of outbound connections to various sites not named. We are just going to block all these and see if we still have a working node . Some examples : 

205.233.216.52.in-addr.arpa     name = s3-1.amazonaws.com.
125.237.210.54.in-addr.arpa     name = ec2-54-210-237-125.compute-1.amazonaws.com.
130.127.120.34.in-addr.arpa     name = 130.127.120.34.bc.googleusercontent.com.
160.113.53.23.in-addr.arpa      name = a23-53-113-160.deploy.static.akamaitechnologies.com.
78.190.250.142.in-addr.arpa     name = ord37s34-in-f14.1e100.net.

**Comment by gkowalski** [comment]
Since it's not a requirement to run these docker images under a container orchestrator,  where it seems much easier to fine tune network control,  would it be better for each docker container to define it's own endpoints via an iptables control script ? In this way we have a documented list of endpoints for each container that we all agree on. This should also not impact your current AWS infrastructure .

**Comment by thomasyu888** [comment]
> So the downloaded docker images from a random person only has access to the "submission" docker network ? Thought we went thru some work to give it access to other docker images on localhost:8080 ?

No the docker images from a random person only has access to the "submission" docker network

**Comment by thomasyu888** [comment]
> Since it's not a requirement to run these docker images under a container orchestrator, where it seems much easier to fine tune network control, would it be better for each docker container to define it's own endpoints via an iptables control script ? In this way we have a documented list of endpoints for each container that we all agree on. This should also not impact your current AWS infrastructure .

Are you saying that each service would live in its own endpoint essentially?  That how we currently have it.  Each service has its own ec2.
