### ISSUE TITLE
Deploy Mayo Clinic dataset

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#92]
These two datasets support the PHI annotation tasks:

- [i2b2 dataset](https://www.synapse.org/#!Synapse:syn26403524)
- [Mayo Clinic dataset](https://www.synapse.org/#!Synapse:syn26403525)

Technically the i2b2 dataset has not changed since the last version so we can skip updating it. Only the Mayo Clinic dataset should be deployed (only the evaluation set).

Note that this version of the Mayo Clinic dataset only includes `Date` and `Person Name` annotations. A future version may include additional types. At this time, only tools submitted to the date and person name annotation tasks should be evaluated against the Mayo Clinic dataset.

Tasks:

- [x] Convert Mayo Clinic raw dataset in XML format to the NLP Sandbox schemas
- [x] #93
- [x] #94
- [x] #95

Tagging the entire @nlpsandbox/team in case you are interested in following the progress of this significant milestone. :)

**Comment by thomasyu888** [comment]
Do you have the dataset name and dataset version you would like me to adopt?

**Comment by tschaffter** [comment]
@thomasyu888 Dataset name can be `mayo-clinic`. Is the version a date? If yes, please use the date when [the dataset](https://www.synapse.org/#!Synapse:syn26403525) has been generated and pushed to Synapse.

**Comment by thomasyu888** [comment]
@tschaffter The pieces are basically there.  You can try submitting to the date and person queues now.  I just need to put together the leaderboard / dashboards now.

Heres an example dashboard: https://www.synapse.org/#!Synapse:syn22277124/wiki/608220.  Its going to get more and more wide as we add more centers.

**Comment by tschaffter** [comment]
@yy6linda Can you try submitting the example PHI annotator tool"?

**Comment by thomasyu888** [comment]
> ... Dataset name can be mayo-clinic. Is the version a date? If yes, please use the date when the dataset has been generated and pushed to Synapse.

@tschaffter Are you sure about the dataset name being `mayo-clinic-phi` or would you prefer `mayo-phi`?  I would like to not have to change it again.

**Comment by tschaffter** [comment]
@thomasyu888 You know what, let's keep the current name as it is. There will probably a new version of the dataset next year and we can change the name at that time. So nothing else to do for the dataset name.

**Comment by tschaffter** [comment]
Done
