### ISSUE TITLE
Update submission and leaderboard tables for the date and person name annotation tasks

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox#95]

**Comment by thomasyu888** [comment]
@tschaffter 

I noticed for the leaderboards we had conditions like: `MCW_submission_status = 'SCORED'`

The problem with adding `Mayo_submission_status = 'SCORED'` is that the existing submissions aren't scored on the Mayo data so no rows will be returned.  We could maybe say `(Mayo_submission_status = 'SCORED' or Mayo_submission_status is null)` but that might have other weird implications.


View the leaderboards in staging to see if you like them:
* date: https://www.synapse.org/#!Synapse:syn22277124/wiki/608039
* person: https://www.synapse.org/#!Synapse:syn22277124/wiki/608040

Dashboards:
* date: https://www.synapse.org/#!Synapse:syn22277124/wiki/608220
* person: https://www.synapse.org/#!Synapse:syn22277124/wiki/608221

Are we not supporting the other annotator types for mayo?

**Comment by tschaffter** [comment]
> Are we not supporting the other annotator types for mayo?

For now Mayo only has Date and Person name annotation so let's only use the Mayo dataset for these tasks.

**Comment by tschaffter** [comment]
Done
